<?php
/** Shared publication runtime contracts. */
declare(strict_types=1);
if (! defined('ABSPATH')) { exit; }
if (! class_exists('NLH_Publication_Runtime')) {
final class NLH_Publication_Runtime {
    private array $config;
    public function __construct(array $config) { $this->config=$config; add_action('rest_api_init',[$this,'register_routes']); add_action('wp_enqueue_scripts',[$this,'enqueue_assets']); add_action('wp_head',[$this,'render_metadata'],4); }
    public function register_routes(): void {
        $ns=(string)$this->config['rest_namespace'];
        register_rest_route($ns,'/discover',['methods'=>WP_REST_Server::READABLE,'permission_callback'=>'__return_true','callback'=>[$this,'discover'],'args'=>['post_type'=>['sanitize_callback'=>'sanitize_key'],'search'=>['sanitize_callback'=>'sanitize_text_field'],'taxonomy'=>['sanitize_callback'=>'sanitize_key'],'terms'=>['sanitize_callback'=>'sanitize_text_field'],'page'=>['sanitize_callback'=>'absint','default'=>1],'per_page'=>['sanitize_callback'=>'absint','default'=>12]]]);
        register_rest_route($ns,'/applications',['methods'=>WP_REST_Server::READABLE,'permission_callback'=>'__return_true','callback'=>fn():WP_REST_Response=>new WP_REST_Response(['items'=>apply_filters('nlh_'.$this->key().'_applications',$this->config['applications']??[])])]);
        register_rest_route($ns,'/commerce',['methods'=>WP_REST_Server::READABLE,'permission_callback'=>'__return_true','callback'=>[$this,'commerce']]);
        register_rest_route($ns,'/saved',[
            ['methods'=>WP_REST_Server::READABLE,'permission_callback'=>static fn():bool=>is_user_logged_in(),'callback'=>[$this,'saved_get']],
            ['methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>static fn():bool=>is_user_logged_in(),'callback'=>[$this,'saved_add'],'args'=>['item_id'=>['required'=>true,'sanitize_callback'=>'absint'],'item_type'=>['sanitize_callback'=>'sanitize_key','default'=>'post']]],
            ['methods'=>WP_REST_Server::DELETABLE,'permission_callback'=>static fn():bool=>is_user_logged_in(),'callback'=>[$this,'saved_delete'],'args'=>['item_id'=>['required'=>true,'sanitize_callback'=>'absint']]],
        ]);
        register_rest_route($ns,'/account',[
            ['methods'=>WP_REST_Server::READABLE,'permission_callback'=>static fn():bool=>is_user_logged_in(),'callback'=>[$this,'account_get']],
            ['methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>static fn():bool=>is_user_logged_in(),'callback'=>[$this,'account_update']],
        ]);
    }
    public function discover(WP_REST_Request $request): WP_REST_Response {
        $allowed=array_values(array_filter(array_map('sanitize_key',$this->config['discover_post_types']??['post']))); $post_type=sanitize_key((string)($request['post_type']?:$allowed[0]));
        if(!in_array($post_type,$allowed,true)){return new WP_REST_Response(['code'=>'invalid_post_type'],400);} $per_page=min(48,max(1,(int)$request['per_page']));
        $args=['post_type'=>$post_type,'post_status'=>'publish','s'=>(string)$request['search'],'paged'=>max(1,(int)$request['page']),'posts_per_page'=>$per_page,'ignore_sticky_posts'=>true];
        $taxonomy=sanitize_key((string)$request['taxonomy']); $terms=array_filter(array_map('sanitize_title',explode(',',(string)$request['terms'])));
        if($taxonomy&&$terms&&taxonomy_exists($taxonomy)&&is_object_in_taxonomy($post_type,$taxonomy)){$args['tax_query']=[['taxonomy'=>$taxonomy,'field'=>'slug','terms'=>$terms]];}
        $query=new WP_Query($args); $items=array_map(static fn(WP_Post $post):array=>['id'=>(int)$post->ID,'type'=>$post->post_type,'title'=>get_the_title($post),'excerpt'=>wp_strip_all_tags(get_the_excerpt($post)),'url'=>get_permalink($post),'featuredMedia'=>get_post_thumbnail_id($post),'modified'=>get_post_modified_time(DATE_ATOM,true,$post)],$query->posts);
        return new WP_REST_Response(['items'=>$items,'page'=>(int)$args['paged'],'perPage'=>$per_page,'total'=>(int)$query->found_posts,'pages'=>(int)$query->max_num_pages]);
    }
    public function saved_get(): WP_REST_Response { return new WP_REST_Response(['items'=>$this->saved_items()]); }
    public function saved_add(WP_REST_Request $request): WP_REST_Response { $post=get_post((int)$request['item_id']); if(!$post instanceof WP_Post||$post->post_status!=='publish'){return new WP_REST_Response(['code'=>'item_not_found'],404);} $items=$this->saved_items(); $items[(string)$post->ID]=['id'=>(int)$post->ID,'type'=>sanitize_key((string)$request['item_type']),'savedAt'=>gmdate(DATE_ATOM)]; update_user_meta(get_current_user_id(),$this->saved_meta_key(),array_values($items)); return new WP_REST_Response(['items'=>array_values($items)],201); }
    public function saved_delete(WP_REST_Request $request): WP_REST_Response { $items=$this->saved_items(); unset($items[(string)(int)$request['item_id']]); update_user_meta(get_current_user_id(),$this->saved_meta_key(),array_values($items)); return new WP_REST_Response(['items'=>array_values($items)]); }
    public function account_get(): WP_REST_Response { return new WP_REST_Response(['preferences'=>$this->preferences()]); }
    public function account_update(WP_REST_Request $request): WP_REST_Response { $body=$request->get_json_params(); $prefs=['emailUpdates'=>!empty($body['emailUpdates']),'recommendationMode'=>in_array(($body['recommendationMode']??''),['balanced','practical','exploratory'],true)?$body['recommendationMode']:'balanced','reducedMotionPreference'=>!empty($body['reducedMotionPreference'])]; update_user_meta(get_current_user_id(),$this->preferences_meta_key(),$prefs); return new WP_REST_Response(['preferences'=>$prefs]); }
    public function commerce(): WP_REST_Response { $items=[];$adapter='editorial-contract'; if(function_exists('wc_get_products')){$adapter='woocommerce';foreach(wc_get_products(['status'=>'publish','limit'=>12]) as $product){$items[]=['id'=>(int)$product->get_id(),'title'=>$product->get_name(),'url'=>$product->get_permalink(),'priceHtml'=>wp_kses_post($product->get_price_html()),'availability'=>$product->is_in_stock()?'in-stock':'out-of-stock'];}}else{$items=apply_filters('nlh_'.$this->key().'_commerce_collections',$this->config['commerce_collections']??[]);} return new WP_REST_Response(['adapter'=>$adapter,'items'=>$items,'checkoutOwnedByTheme'=>false]); }
    public function enqueue_assets(): void { $handle='nlh-'.$this->key().'-runtime'; wp_enqueue_script($handle,plugins_url('assets/publication-runtime.js',(string)$this->config['plugin_file']),[],(string)$this->config['version'],true); $consent=function_exists('wp_has_consent')?(bool)wp_has_consent('statistics'):false; $consent=(bool)apply_filters('nlh_'.$this->key().'_statistics_consent',$consent); wp_localize_script($handle,'NLHPublicationRuntime',['key'=>$this->key(),'restRoot'=>esc_url_raw(rest_url((string)$this->config['rest_namespace'])),'nonce'=>is_user_logged_in()?wp_create_nonce('wp_rest'):'','loggedIn'=>is_user_logged_in(),'statisticsConsent'=>$consent,'pageWorlds'=>$this->config['page_worlds']??[]]); }
    public function render_metadata(): void { if(is_admin()||defined('WPSEO_VERSION')||defined('RANK_MATH_VERSION')||defined('AIOSEO_VERSION')){return;} $title=wp_get_document_title();$description=is_singular()?wp_strip_all_tags(get_the_excerpt()?:get_bloginfo('description')):get_bloginfo('description');$canonical=is_singular()?wp_get_canonical_url():home_url(add_query_arg([],$GLOBALS['wp']->request??'')); echo "\n<meta property=\"og:title\" content=\"".esc_attr($title)."\"><meta property=\"og:description\" content=\"".esc_attr($description)."\"><meta property=\"og:url\" content=\"".esc_url($canonical)."\"><meta property=\"og:type\" content=\"".(is_singular('post')?'article':'website')."\"><meta name=\"twitter:card\" content=\"summary_large_image\">"; $type=(is_front_page()||is_post_type_archive())?'CollectionPage':(is_singular('post')?'Article':'WebPage');$schema=['@context'=>'https://schema.org','@type'=>$type,'name'=>$title,'description'=>$description,'url'=>$canonical,'isPartOf'=>['@type'=>'WebSite','name'=>(string)$this->config['publication'],'url'=>home_url('/')]];echo "\n<script type=\"application/ld+json\">".wp_json_encode($schema,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).'</script>'."\n"; }
    private function key(): string{return sanitize_key((string)$this->config['key']);} private function saved_meta_key():string{return 'nlh_'.$this->key().'_saved_items';} private function preferences_meta_key():string{return 'nlh_'.$this->key().'_preferences';}
    private function saved_items():array{$stored=get_user_meta(get_current_user_id(),$this->saved_meta_key(),true);$indexed=[];foreach(is_array($stored)?$stored:[] as $item){if(!empty($item['id'])){$indexed[(string)(int)$item['id']]=$item;}}return $indexed;}
    private function preferences():array{$stored=get_user_meta(get_current_user_id(),$this->preferences_meta_key(),true);return wp_parse_args(is_array($stored)?$stored:[],['emailUpdates'=>false,'recommendationMode'=>'balanced','reducedMotionPreference'=>false]);}
}}
