<?php
/**
 * Title: Conditions and stewardship pathway
 * Slug: hook-the-horizon/conditions-stewardship-pathway
 * Categories: featured
 * Inserter: true
 */
?>
<!-- wp:group {"tagName":"main","align":"full","className":"hth-pathway","layout":{"type":"constrained"}} --><main class="wp-block-group alignfull hth-pathway"><!-- wp:group {"align":"wide"} --><div class="wp-block-group alignwide"><!-- wp:paragraph {"className":"hth-kicker"} --><p class="hth-kicker">Read the conditions. Protect the water.</p><!-- /wp:paragraph --><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Observe first. Pack for change. Stop when the day says stop.</h1><!-- /wp:heading --><!-- wp:paragraph --><p>This pathway turns visible conditions into a field card without inventing fish, access, safety or performance.</p><!-- /wp:paragraph --></div><!-- /wp:group --><!-- wp:list {"ordered":true} --><ol><li><a href="/how-to-read-moving-water-before-the-first-cast/">Observe moving water</a></li><li><a href="/pack-for-the-decision-not-the-fantasy/">Pack for changing conditions</a></li><li><a href="/weather-stops-that-should-end-the-fishing-plan/">Use current weather and access stops</a></li><li><a href="/a-field-note-is-only-useful-if-it-changes-the-next-decision/">Write a useful field note</a></li><li><a href="/how-to-share-a-fishing-story-without-sharing-the-spot/">Tell the story without revealing the spot</a></li></ol><!-- /wp:list --><!-- wp:group {"align":"wide","className":"hth-pathway__output"} --><div class="wp-block-group alignwide hth-pathway__output"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading">First useful output: a conditions and stewardship field card</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Separate observation, forecast, uncertainty, stop signals, packing choices, field-note prompts and privacy checks.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="/honey-hole-intelligence/">Continue to Honey Hole Intelligence</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></main><!-- /wp:group -->
